/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Dialog;

import Dto.Factura;
import Dto.Persona;
import Dto.Producto;
import Logica.LogicaNegocio;
import Logica.LogicaTemas;
import TableModels.PersonasTableModel;
import TableModels.ProductoTableModel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Plam
 */
public class DialogFactura extends javax.swing.JDialog {

    private List<JLabel> listaLabelsH2;
    private List<JLabel> listaLabelsH1;
    private LogicaNegocio logica;
    private PersonasTableModel ptm;
    private ProductoTableModel prodtm;
    private List<Producto> listaProductos;
    private double precioTotal = 0d;
    private JFrame parent;
    private Factura factura;

    /**
     * Creates new form DialogNuevaFactura
     */
    public DialogFactura(JFrame parent, boolean modal, LogicaNegocio logica, Factura f) {
        super(parent, modal);
        this.logica = logica;
        initComponents();
        this.setLocationRelativeTo(null);

        this.parent = parent;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        ptm = new PersonasTableModel(logica.getListaPersonas());
        jComboBoxPersonas.setModel(logica.getPersonasComboBoxModel());
        jComboBoxProductos.setModel(logica.getProductosComboBoxModel());
        
        if (f != null) {
            this.factura = f;
            jLabelH2FechaNuevaFactura.setText("- " + sdf.format(this.factura.getFecha()) + " -");
            listaProductos = this.factura.getListaProductos();
            
            Persona p = logica.getPersonaPorIDFactura(this.factura.getCodFactura());

            String nombre = p.getNombre() + " " + p.getApellido();
            jComboBoxPersonas.setSelectedItem(nombre);
            System.out.println(nombre);
            
            jTextAreaTrabajos.setText(this.factura.getTrabajos());
            jLabel1H2PrecioTotal.setText("" + this.factura.getPrecio());

            prodtm = new ProductoTableModel(listaProductos);
            
            jButton2.setVisible(false);
            jButton1.setVisible(false);
            jButtonAddProductoFactura.setVisible(false);
            jButtonBorrarProductoFactura.setVisible(false);
            jButtonNuevaFactura.setVisible(false);
        } else {
            jLabelH2FechaNuevaFactura.setText(sdf.format(new Date()));
            listaProductos = new ArrayList<>();
            prodtm = new ProductoTableModel(listaProductos);
        }

        jTableProductos.setModel(prodtm);
        //prodtm.setCellEditable(0, 0, modal);

        

        listaLabelsH1 = new ArrayList<>();
        listaLabelsH1.add(jLabel1H1DialogNuevaFactura);

        listaLabelsH2 = new ArrayList<>();
        listaLabelsH2.add(jLabel1H2);
        listaLabelsH2.add(jLabel2H2);
        listaLabelsH2.add(jLabel3H2);
        listaLabelsH2.add(jLabel6H2);
        listaLabelsH2.add(jLabel9H2);
        listaLabelsH2.add(jLabel1H2PrecioTotal);
        listaLabelsH2.add(jLabelH2FechaNuevaFactura);

        LogicaTemas.addListJLabel("JLabelH1NuevaNota", listaLabelsH1);
        LogicaTemas.addListJLabel("JLabelH2ANuevaFactura", listaLabelsH2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1H2 = new javax.swing.JLabel();
        jLabel2H2 = new javax.swing.JLabel();
        jLabel3H2 = new javax.swing.JLabel();
        jLabelH2FechaNuevaFactura = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jButtonAddProductoFactura = new javax.swing.JButton();
        jButtonBorrarProductoFactura = new javax.swing.JButton();
        jButtonNuevaFactura = new javax.swing.JButton();
        jButtonCancelarNuevaFactura = new javax.swing.JButton();
        jLabel1H1DialogNuevaFactura = new javax.swing.JLabel();
        jLabel1H2PrecioTotal = new javax.swing.JLabel();
        jLabel6H2 = new javax.swing.JLabel();
        jComboBoxPersonas = new javax.swing.JComboBox<>();
        jLabel9H2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTrabajos = new javax.swing.JTextArea();
        jComboBoxProductos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel1H2.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jLabel1H2.text")); // NOI18N

        jLabel2H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel2H2.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jLabel2H2.text")); // NOI18N

        jLabel3H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel3H2.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jLabel3H2.text")); // NOI18N

        jLabelH2FechaNuevaFactura.setFont(LogicaTemas.TEXT_FONT);
        jLabelH2FechaNuevaFactura.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jLabelH2FechaNuevaFactura.text")); // NOI18N

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        jButtonAddProductoFactura.setFont(LogicaTemas.BUTTON_FONT);
        jButtonAddProductoFactura.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jButtonAddProductoFactura.text")); // NOI18N
        jButtonAddProductoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProductoFacturaActionPerformed(evt);
            }
        });

        jButtonBorrarProductoFactura.setFont(LogicaTemas.BUTTON_FONT);
        jButtonBorrarProductoFactura.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jButtonBorrarProductoFactura.text")); // NOI18N
        jButtonBorrarProductoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarProductoFacturaActionPerformed(evt);
            }
        });

        jButtonNuevaFactura.setFont(LogicaTemas.BUTTON_FONT);
        jButtonNuevaFactura.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jButtonNuevaFactura.text")); // NOI18N
        jButtonNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaFacturaActionPerformed(evt);
            }
        });

        jButtonCancelarNuevaFactura.setFont(LogicaTemas.BUTTON_FONT);
        jButtonCancelarNuevaFactura.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jButtonCancelarNuevaFactura.text")); // NOI18N
        jButtonCancelarNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarNuevaFacturaActionPerformed(evt);
            }
        });

        jLabel1H1DialogNuevaFactura.setFont(LogicaTemas.TEXT_FONT_H1);
        jLabel1H1DialogNuevaFactura.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jLabel1H1DialogNuevaFactura.text")); // NOI18N

        jLabel1H2PrecioTotal.setFont(LogicaTemas.TEXT_FONT);
        jLabel1H2PrecioTotal.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jLabel1H2PrecioTotal.text")); // NOI18N

        jLabel6H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel6H2.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jLabel6H2.text")); // NOI18N

        jComboBoxPersonas.setModel(logica.getClientesComboBoxModel());

        jLabel9H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel9H2.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jLabel9H2.text")); // NOI18N

        jTextAreaTrabajos.setColumns(20);
        jTextAreaTrabajos.setRows(5);
        jScrollPane2.setViewportView(jTextAreaTrabajos);

        jButton1.setFont(LogicaTemas.BUTTON_FONT);
        jButton1.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(LogicaTemas.BUTTON_FONT);
        jButton2.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnImprimir.setFont(LogicaTemas.BUTTON_FONT);
        btnImprimir.setText(org.openide.util.NbBundle.getMessage(DialogFactura.class, "DialogFactura.btnImprimir.text")); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1H1DialogNuevaFactura)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1H2)
                            .addComponent(jLabel6H2)
                            .addComponent(jLabel9H2)
                            .addComponent(jLabel3H2))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBoxProductos, 0, 276, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAddProductoFactura)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBorrarProductoFactura)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelH2FechaNuevaFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxPersonas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2H2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1H2PrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCancelarNuevaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonNuevaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1H1DialogNuevaFactura)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1H2)
                    .addComponent(jLabelH2FechaNuevaFactura))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6H2)
                    .addComponent(jComboBoxPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9H2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddProductoFactura)
                    .addComponent(jButtonBorrarProductoFactura)
                    .addComponent(jLabel3H2)
                    .addComponent(jComboBoxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2H2)
                    .addComponent(jLabel1H2PrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonNuevaFactura)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnImprimir)
                        .addComponent(jButtonCancelarNuevaFactura)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaFacturaActionPerformed
        String nombre = (String) jComboBoxPersonas.getSelectedItem();
        
        Persona p = logica.getPersonaPorNombre(nombre);
        if (p != null) {
            String trabajos = jTextAreaTrabajos.getText();
            logica.addFactura(precioTotal, p.getCodPersona(), listaProductos, trabajos, parent);
        } else { 
            return;
        }
        dispose();
    }//GEN-LAST:event_jButtonNuevaFacturaActionPerformed

    private void jButtonCancelarNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarNuevaFacturaActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarNuevaFacturaActionPerformed

    private void jButtonAddProductoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProductoFacturaActionPerformed
        String nomProducto = (String) jComboBoxProductos.getSelectedItem();
        Producto p = logica.getProductoPorNombre(nomProducto);
        if (p != null) {
            //if (listaProductos.contains(p)) {
            for (Producto producto : listaProductos) {
                if (producto.getNombre().equals(p.getNombre())) {
                    producto.setCantidad((producto.getCantidad() + 1));
                    precioTotal += producto.getPrecio();
                    jLabel1H2PrecioTotal.setText(precioTotal + "");
                    jTableProductos.setModel(new ProductoTableModel(listaProductos));
                    return;
                }
            }

            p.setCantidad(1);
            listaProductos.add(p);
            jTableProductos.setModel(new ProductoTableModel(listaProductos));
            precioTotal += p.getPrecio();
            jLabel1H2PrecioTotal.setText(precioTotal + "");
        }


    }//GEN-LAST:event_jButtonAddProductoFacturaActionPerformed

    private void jButtonBorrarProductoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarProductoFacturaActionPerformed
        int ID_producto = (int) jTableProductos.getValueAt(jTableProductos.getSelectedRow(), 0);
        for (int i = 0; i < listaProductos.size(); i++) {
            if (listaProductos.get(i).getCodProducto() == ID_producto) {
                precioTotal -= listaProductos.get(i).getPrecio();
                jLabel1H2PrecioTotal.setText(precioTotal + "");
                listaProductos.remove(i);
                jTableProductos.setModel(new ProductoTableModel(listaProductos));

            }
        }
    }//GEN-LAST:event_jButtonBorrarProductoFacturaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DialogPersona dialog = new DialogPersona(parent, true, logica, null);
        dialog.setVisible(true);
        jComboBoxPersonas.setModel(logica.getPersonasComboBoxModel());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DialogProducto dialog = new DialogProducto(parent, true, logica, null);
        dialog.setVisible(true);
        jComboBoxProductos.setModel(logica.getProductosComboBoxModel());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        if (factura != null) {
            logica.imprimirInformeFactura(factura);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    public static DialogFactura newInstance(JFrame parent, boolean modal, LogicaNegocio logica, Factura f) {
        return new DialogFactura(parent, modal, logica, f);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAddProductoFactura;
    private javax.swing.JButton jButtonBorrarProductoFactura;
    private javax.swing.JButton jButtonCancelarNuevaFactura;
    private javax.swing.JButton jButtonNuevaFactura;
    private javax.swing.JComboBox<String> jComboBoxPersonas;
    private javax.swing.JComboBox<String> jComboBoxProductos;
    private javax.swing.JLabel jLabel1H1DialogNuevaFactura;
    private javax.swing.JLabel jLabel1H2;
    private javax.swing.JLabel jLabel1H2PrecioTotal;
    private javax.swing.JLabel jLabel2H2;
    private javax.swing.JLabel jLabel3H2;
    private javax.swing.JLabel jLabel6H2;
    private javax.swing.JLabel jLabel9H2;
    private javax.swing.JLabel jLabelH2FechaNuevaFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextArea jTextAreaTrabajos;
    // End of variables declaration//GEN-END:variables
}
