/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Dialog;

import Dto.Usuario;
import Logica.LogicaNegocio;
import Logica.LogicaTemas;

/**
 *
 * @author bahguta
 */
public class DialogRegistrar extends javax.swing.JDialog {

    private LogicaNegocio logica;
    private Usuario usuario;

    /**
     * Creates new form DialogRegistrar
     */
    public DialogRegistrar(java.awt.Frame parent, boolean modal, LogicaNegocio logica) {
        super(parent, modal);
        initComponents();
        this.logica = logica;
        this.usuario = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegistrar = new javax.swing.JButton();
        jPasswordFieldConfirm = new javax.swing.JPasswordField();
        jPasswordFieldLoginPass = new javax.swing.JPasswordField();
        jTextFieldLoginUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelConfirmar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButtonRegistrar.setFont(LogicaTemas.BUTTON_FONT);
        jButtonRegistrar.setText(org.openide.util.NbBundle.getMessage(DialogRegistrar.class, "DialogRegistrar.jButtonRegistrar.text")); // NOI18N
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jPasswordFieldConfirm.setFont(LogicaTemas.TEXT_FONT);
        jPasswordFieldConfirm.setText(org.openide.util.NbBundle.getMessage(DialogRegistrar.class, "DialogRegistrar.jPasswordFieldConfirm.text")); // NOI18N

        jPasswordFieldLoginPass.setFont(LogicaTemas.TEXT_FONT);
        jPasswordFieldLoginPass.setText(org.openide.util.NbBundle.getMessage(DialogRegistrar.class, "DialogRegistrar.jPasswordFieldLoginPass.text")); // NOI18N

        jTextFieldLoginUsuario.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldLoginUsuario.setText(org.openide.util.NbBundle.getMessage(DialogRegistrar.class, "DialogRegistrar.jTextFieldLoginUsuario.text")); // NOI18N

        jLabel2.setFont(LogicaTemas.TEXT_FONT_H1);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(org.openide.util.NbBundle.getMessage(DialogRegistrar.class, "DialogRegistrar.jLabel2.text")); // NOI18N

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jLabelIcon.setText(org.openide.util.NbBundle.getMessage(DialogRegistrar.class, "DialogRegistrar.jLabelIcon.text")); // NOI18N

        jLabel9.setFont(LogicaTemas.TEXT_FONT);
        jLabel9.setText(org.openide.util.NbBundle.getMessage(DialogRegistrar.class, "DialogRegistrar.jLabel9.text")); // NOI18N

        jLabel10.setFont(LogicaTemas.TEXT_FONT);
        jLabel10.setText(org.openide.util.NbBundle.getMessage(DialogRegistrar.class, "DialogRegistrar.jLabel10.text")); // NOI18N

        jLabelConfirmar.setFont(LogicaTemas.TEXT_FONT);
        jLabelConfirmar.setText(org.openide.util.NbBundle.getMessage(DialogRegistrar.class, "DialogRegistrar.jLabelConfirmar.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelIcon)
                .addContainerGap(408, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistrar)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabelConfirmar))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldLoginUsuario)
                                .addComponent(jPasswordFieldLoginPass, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(jPasswordFieldConfirm)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistrar)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordFieldLoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelConfirmar)
                        .addComponent(jPasswordFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(38, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        if (!logica.isConexionExitosa()) {
            return;
        }
        String nombre = jTextFieldLoginUsuario.getText();
        String pass = jPasswordFieldLoginPass.getPassword().toString();
        String passConfirm = jPasswordFieldConfirm.getPassword().toString();
        if (pass.equals(passConfirm)) {
            if (logica.registrarUsuario(nombre, pass)) {
                this.usuario = logica.getUsuario(nombre, pass);
                logica.setUsuario(this.usuario);
                setVisible(false);
            }
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelConfirmar;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JPasswordField jPasswordFieldConfirm;
    private javax.swing.JPasswordField jPasswordFieldLoginPass;
    private javax.swing.JTextField jTextFieldLoginUsuario;
    // End of variables declaration//GEN-END:variables
}
