/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Dialog;

import Dto.NotaLibroDiario;
import Logica.LogicaNegocio;
import Logica.LogicaTemas;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class DialogNotaLibro extends javax.swing.JDialog {

    private List<JLabel> listaLabelsH2;
    private List<JLabel> listaLabelsH1;
    private LogicaNegocio logica;
    private NotaLibroDiario nota;
    private SimpleDateFormat sdf;

    /**
     * Creates new form DialogNotaLibro
     */
    public DialogNotaLibro(JFrame parent, boolean modal, LogicaNegocio logica, NotaLibroDiario nota) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.logica = logica;
        this.nota = nota;
        sdf = new SimpleDateFormat("dd/MM/yyyy");
        if (this.nota != null) {
            jLabel1H2CodNota.setText(this.nota.getCodNota() + "");
            jLabel1H2Fecha.setText(sdf.format(this.nota.getFecha()));
            jTextFieldDebeNota.setText(this.nota.getDebe() + "");
            jTextFieldHaberNota.setText(this.nota.getHaber() + "");
            jTextAreaDetalleNota.setText(this.nota.getDetalle());
        } else {
            jLabel1H2CodNota.setText("----");
            //System.out.println("else " + sdf.format(GregorianCalendar.getInstance().getTime()));
            jLabel1H2Fecha.setText(sdf.format(GregorianCalendar.getInstance().getTime()));
        }

        listaLabelsH1 = new ArrayList<>();
        listaLabelsH1.add(jLabel1H1DialogNota);

        listaLabelsH2 = new ArrayList<>();
        listaLabelsH2.add(jLabel1H2);
        listaLabelsH2.add(jLabel2H2);
        listaLabelsH2.add(jLabel3H2);
        listaLabelsH2.add(jLabel4H2);
        listaLabelsH2.add(jLabel5H2);
        listaLabelsH2.add(jLabel1H2CodNota);
        listaLabelsH2.add(jLabel1H2Fecha);

        LogicaTemas.addListJLabel("JLabelH1NuevaNota", listaLabelsH1);
        LogicaTemas.addListJLabel("JLabelH2DialogNota", listaLabelsH2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2H2 = new javax.swing.JLabel();
        jLabel3H2 = new javax.swing.JLabel();
        jLabel4H2 = new javax.swing.JLabel();
        jTextFieldDebeNota = new javax.swing.JTextField();
        jTextFieldHaberNota = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDetalleNota = new javax.swing.JTextArea();
        jButtonOKNota = new javax.swing.JButton();
        jButtonCancelarNota = new javax.swing.JButton();
        jLabel1H2 = new javax.swing.JLabel();
        jLabel1H2Fecha = new javax.swing.JLabel();
        jLabel5H2 = new javax.swing.JLabel();
        jLabel1H2CodNota = new javax.swing.JLabel();
        jLabel1H1DialogNota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel2H2.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jLabel2H2.text")); // NOI18N

        jLabel3H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel3H2.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jLabel3H2.text")); // NOI18N

        jLabel4H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel4H2.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jLabel4H2.text")); // NOI18N

        jTextFieldDebeNota.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldDebeNota.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jTextFieldDebeNota.text")); // NOI18N

        jTextFieldHaberNota.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldHaberNota.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jTextFieldHaberNota.text")); // NOI18N

        jTextAreaDetalleNota.setColumns(20);
        jTextAreaDetalleNota.setFont(LogicaTemas.TEXT_FONT);
        jTextAreaDetalleNota.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDetalleNota);

        jButtonOKNota.setFont(LogicaTemas.BUTTON_FONT);
        jButtonOKNota.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jButtonOKNota.text")); // NOI18N
        jButtonOKNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKNotaActionPerformed(evt);
            }
        });

        jButtonCancelarNota.setFont(LogicaTemas.BUTTON_FONT);
        jButtonCancelarNota.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jButtonCancelarNota.text")); // NOI18N
        jButtonCancelarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarNotaActionPerformed(evt);
            }
        });

        jLabel1H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel1H2.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jLabel1H2.text")); // NOI18N

        jLabel1H2Fecha.setFont(LogicaTemas.TEXT_FONT);
        jLabel1H2Fecha.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jLabel1H2Fecha.text")); // NOI18N

        jLabel5H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel5H2.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jLabel5H2.text")); // NOI18N

        jLabel1H2CodNota.setFont(LogicaTemas.TEXT_FONT);
        jLabel1H2CodNota.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jLabel1H2CodNota.text")); // NOI18N

        jLabel1H1DialogNota.setFont(LogicaTemas.TEXT_FONT_H1);
        jLabel1H1DialogNota.setText(org.openide.util.NbBundle.getMessage(DialogNotaLibro.class, "DialogNotaLibro.jLabel1H1DialogNota.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonOKNota, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5H2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4H2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3H2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2H2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1H2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1H2Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDebeNota, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(jTextFieldHaberNota)
                            .addComponent(jLabel1H2CodNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1H1DialogNota)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1H1DialogNota)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5H2)
                    .addComponent(jLabel1H2CodNota))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1H2)
                    .addComponent(jLabel1H2Fecha))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2H2)
                    .addComponent(jTextFieldDebeNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3H2)
                    .addComponent(jTextFieldHaberNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4H2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOKNota)
                    .addComponent(jButtonCancelarNota))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarNotaActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarNotaActionPerformed

    private void jButtonOKNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKNotaActionPerformed

        try {
            Date fecha = sdf.parse(jLabel1H2Fecha.getText().toString());
            String debe = jTextFieldDebeNota.getText();
            String haber = jTextFieldHaberNota.getText();
            String detalle = jTextAreaDetalleNota.getText();

            if (debe.isEmpty() || haber.isEmpty() || detalle.isEmpty()) {
                return;
            }

            if (this.nota == null) {
                logica.addNota(fecha, Double.valueOf(debe), Double.valueOf(haber), detalle);
            } else {
                logica.moidifcarNota(this.nota.getCodNota(), fecha, Double.valueOf(debe), Double.valueOf(haber), detalle);
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }
        dispose();
    }//GEN-LAST:event_jButtonOKNotaActionPerformed

    public static DialogNotaLibro newInstance(JFrame parent, boolean modal, LogicaNegocio logica, NotaLibroDiario nota) {
        return new DialogNotaLibro(parent, modal, logica, nota);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarNota;
    private javax.swing.JButton jButtonOKNota;
    private javax.swing.JLabel jLabel1H1DialogNota;
    private javax.swing.JLabel jLabel1H2;
    private javax.swing.JLabel jLabel1H2CodNota;
    private javax.swing.JLabel jLabel1H2Fecha;
    private javax.swing.JLabel jLabel2H2;
    private javax.swing.JLabel jLabel3H2;
    private javax.swing.JLabel jLabel4H2;
    private javax.swing.JLabel jLabel5H2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDetalleNota;
    private javax.swing.JTextField jTextFieldDebeNota;
    private javax.swing.JTextField jTextFieldHaberNota;
    // End of variables declaration//GEN-END:variables
}
