/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Main;

import Logica.LogicaNegocio;
import Logica.LogicaTemas;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * El dialogo login hace la conexion inicial con la base de datos<br>
 * a travez del controlador LogicaNegocio.class
 *
 * @author Plam
 */
public class ConexionBBDD extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    private LogicaNegocio logica;
    private JFrame parent;

    //private String nombreLogin;
    //private char[] passLogin;   
    private String host;
    private int puerto;
    private String nomBBDD;
    private String user;
    private char[] pass;

    /**
     * Constructor
     */
    public ConexionBBDD(JFrame parent, boolean modal, LogicaNegocio logica) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.logica = logica;

        //datos conexion
        this.host = "";
        this.puerto = 0;
        this.nomBBDD = "";
        this.user = "";
        this.pass = new char[]{};
//
//        //datos usuario
//        this.nombre = "";
//        this.pass = new char[]{};
    }

    @Override
    public void dispose() {
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
        System.exit(0);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldHost = new javax.swing.JTextField();
        jTextFieldPuerto = new javax.swing.JTextField();
        jTextFieldNomBBDD = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldpass = new javax.swing.JPasswordField();
        jButtonConnect = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();

        jLabel3.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jLabel3.text")); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jLabel11.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(LogicaTemas.TEXT_FONT_H1);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jLabel1.text")); // NOI18N

        jLabel4.setFont(LogicaTemas.TEXT_FONT);
        jLabel4.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jLabel4.text")); // NOI18N

        jLabel5.setFont(LogicaTemas.TEXT_FONT);
        jLabel5.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jLabel5.text")); // NOI18N

        jLabel6.setFont(LogicaTemas.TEXT_FONT);
        jLabel6.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jLabel6.text")); // NOI18N

        jLabel7.setFont(LogicaTemas.TEXT_FONT);
        jLabel7.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jLabel7.text")); // NOI18N

        jLabel8.setFont(LogicaTemas.TEXT_FONT);
        jLabel8.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jLabel8.text")); // NOI18N

        jTextFieldHost.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldHost.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jTextFieldHost.text")); // NOI18N

        jTextFieldPuerto.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldPuerto.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jTextFieldPuerto.text")); // NOI18N

        jTextFieldNomBBDD.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldNomBBDD.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jTextFieldNomBBDD.text")); // NOI18N

        jTextFieldUsuario.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldUsuario.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jTextFieldUsuario.text")); // NOI18N

        jPasswordFieldpass.setFont(LogicaTemas.TEXT_FONT);
        jPasswordFieldpass.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jPasswordFieldpass.text")); // NOI18N

        jButtonConnect.setFont(LogicaTemas.BUTTON_FONT);
        jButtonConnect.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jButtonConnect.text")); // NOI18N
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jButtonLimpiar.setFont(LogicaTemas.BUTTON_FONT);
        jButtonLimpiar.setText(org.openide.util.NbBundle.getMessage(ConexionBBDD.class, "ConexionBBDD.jButtonLimpiar.text")); // NOI18N
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 163, Short.MAX_VALUE)
                        .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHost)
                            .addComponent(jTextFieldPuerto)
                            .addComponent(jTextFieldNomBBDD)
                            .addComponent(jTextFieldUsuario)
                            .addComponent(jPasswordFieldpass))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNomBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordFieldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConnect)
                    .addComponent(jButtonLimpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para limpiar los cambos para poder rellenarlo de nuevo
     *
     * @param evt
     */
    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        //jTextFieldLoginUsuario.setText("");
        //jPasswordFieldLoginPass.setText("");
        jTextFieldHost.setText("");
        jTextFieldNomBBDD.setText("");
        jTextFieldPuerto.setText("");
        jTextFieldUsuario.setText("");
        jPasswordFieldpass.setText("");

    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * Metodo para hacer la conexion inicial
     *
     * @param evt
     */

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        //nombreLogin = jTextFieldLoginUsuario.getText();
        //passLogin = jPasswordFieldLoginPass.getPassword();

        //nombreBBDD = jTextFieldUsuariobbdd.getText();
        host = jTextFieldHost.getText();
        if (esNumero(jTextFieldPuerto.getText())) {
            puerto = Integer.valueOf(jTextFieldPuerto.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Puerto NO valido. Introduce un numero entero.");
            return;
        }
        nomBBDD = jTextFieldNomBBDD.getText();
        user = jTextFieldUsuario.getText();
        pass = jPasswordFieldpass.getPassword();

        if (logica.conectBBDD(user, getPass(), host, puerto, nomBBDD)) {
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Datos de la conexion NO Validos.");
        }

        //logica = new LogicaNegocio(parent, nombre, pass.toString(), host, puerto, nombreBBDD);
//            if (esNumero(jTextFieldPuerto.getText())) {
//            } 

    }//GEN-LAST:event_jButtonConnectActionPerformed

    /**
     * Metodo para comprobar si un String es numero
     *
     * @param s
     * @return
     */
    public boolean esNumero(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException e) {
            logger.error(e.getMessage());
        }
        return false;
    }

    /**
     * Metodo para obtener el nombre para la conexion a la base de datos
     *
     * @return
     */
    public String getUser() {
        return user;
    }

    /**
     * Metodo para obtener la contraseña para la conexion a la base de datos
     *
     * @return
     */
    public String getPass() {
        String password = "";

        for (int i = 0; i < pass.length; i++) {
            password += pass[i];
        }
        return password;
    }

    /**
     * Metodo para obtener el host para la conexion a la base de datos
     *
     * @return
     */
    public String getHost() {
        return host;
    }

    /**
     * Metodo para obtener el nombre de la base de datos para la conexion a la
     * base de datos
     *
     * @return
     */
    public String getNomBBDD() {
        return nomBBDD;
    }

    /**
     * Metodo para obtener el puerto para la conexion a la base de datos
     *
     * @return
     */
    public int getPuerto() {
        return puerto;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordFieldpass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldHost;
    private javax.swing.JTextField jTextFieldNomBBDD;
    private javax.swing.JTextField jTextFieldPuerto;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
    private static final org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(ConexionBBDD.class);
}
