/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Main;

import Logica.LogicaTemas;
import javax.swing.JOptionPane;

/**
 *
 * @author Plam
 */
public class Login extends javax.swing.JDialog {
    
    private boolean registrar = false;

    private String nombre, host, nombreBBDD;
    private int puerto;
    private char [] pass;

    private String nombreLogin;
    private char [] passLogin;

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldHost = new javax.swing.JTextField();
        jTextFieldPuerto = new javax.swing.JTextField();
        jTextFieldBBDD = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonConnect = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jPasswordFieldLoginPass = new javax.swing.JPasswordField();
        jTextFieldLoginUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel3.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabel3.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.setFont(LogicaTemas.BUTTON_FONT);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));

        jLabel1.setFont(LogicaTemas.TEXT_FONT_H1);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabel1.text")); // NOI18N

        jLabel2.setFont(LogicaTemas.TEXT_FONT_H1);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabel2.text")); // NOI18N

        jLabel4.setFont(LogicaTemas.TEXT_FONT);
        jLabel4.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabel4.text")); // NOI18N

        jLabel5.setFont(LogicaTemas.TEXT_FONT);
        jLabel5.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabel5.text")); // NOI18N

        jLabel6.setFont(LogicaTemas.TEXT_FONT);
        jLabel6.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabel6.text")); // NOI18N

        jLabel7.setFont(LogicaTemas.TEXT_FONT);
        jLabel7.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabel7.text")); // NOI18N

        jLabel8.setFont(LogicaTemas.TEXT_FONT);
        jLabel8.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabel8.text")); // NOI18N

        jTextFieldHost.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldHost.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jTextFieldHost.text")); // NOI18N

        jTextFieldPuerto.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldPuerto.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jTextFieldPuerto.text")); // NOI18N

        jTextFieldBBDD.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldBBDD.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jTextFieldBBDD.text")); // NOI18N

        jTextFieldUsuario.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldUsuario.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jTextFieldUsuario.text")); // NOI18N

        jPasswordField.setFont(LogicaTemas.TEXT_FONT);
        jPasswordField.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jPasswordField.text")); // NOI18N

        jButtonConnect.setFont(LogicaTemas.BUTTON_FONT);
        jButtonConnect.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jButtonConnect.text")); // NOI18N
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jButtonLimpiar.setFont(LogicaTemas.BUTTON_FONT);
        jButtonLimpiar.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jButtonLimpiar.text")); // NOI18N
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jPasswordFieldLoginPass.setFont(LogicaTemas.TEXT_FONT);
        jPasswordFieldLoginPass.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jPasswordFieldLoginPass.text")); // NOI18N

        jTextFieldLoginUsuario.setFont(LogicaTemas.TEXT_FONT);
        jTextFieldLoginUsuario.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jTextFieldLoginUsuario.text")); // NOI18N

        jLabel9.setFont(LogicaTemas.TEXT_FONT);
        jLabel9.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabel9.text")); // NOI18N

        jLabel10.setFont(LogicaTemas.TEXT_FONT);
        jLabel10.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabel10.text")); // NOI18N

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jLabelIcon.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabelIcon.text")); // NOI18N

        jLabel11.setFont(LogicaTemas.TEXT_FONT);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(org.openide.util.NbBundle.getMessage(Login.class, "Login.jLabel11.text")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelIcon)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLoginUsuario)
                                    .addComponent(jPasswordFieldLoginPass)))
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(373, Short.MAX_VALUE)
                        .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldHost)
                                    .addComponent(jTextFieldPuerto)
                                    .addComponent(jTextFieldBBDD)
                                    .addComponent(jTextFieldUsuario)
                                    .addComponent(jPasswordField))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordFieldLoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConnect)
                    .addComponent(jButtonLimpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldLoginUsuario.setText("");
        jPasswordFieldLoginPass.setText("");
        jTextFieldHost.setText("");
        jTextFieldBBDD.setText("");
        jTextFieldPuerto.setText("");
        jTextFieldUsuario.setText("");
        jPasswordField.setText("");

    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        nombreLogin = jTextFieldLoginUsuario.getText();
        passLogin = jPasswordFieldLoginPass.getPassword();
        System.out.println(passLogin);

        nombre = jTextFieldUsuario.getText();
        pass = jPasswordField.getPassword();
        System.out.println(pass);
        
        host = jTextFieldHost.getText();
        nombreBBDD = jTextFieldBBDD.getText();
        if (esNumero(jTextFieldPuerto.getText())) {
            puerto = Integer.valueOf(jTextFieldPuerto.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Puerto NO valido. Introduce un numero entero.");
            return;
        }
        setVisible(false);
    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        registrar = true;
        jComboBox1.setSelectedIndex(1);
        jComboBox1.setEnabled(false);
        
    }//GEN-LAST:event_jLabel11MouseClicked

    public boolean esNumero(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException e) {
            e.getMessage();
        }
        return false;
    }

    public boolean isRegistrar() {
        return registrar;
    }

    

    public String getNombreLogin() {
        return nombreLogin;
    }

    public String getPassLogin() {
        String passLog = String.valueOf(passLogin);
        return passLog;
    }

    public String getNombre() {
        return nombre;
    }

    public String getPass() {
        String password = "";
        
        for (int i = 0; i < pass.length; i++) {
            password += pass[i];
        }
        System.out.println(password);
        return password;
    }

    public String getHost() {
        return host;
    }

    public String getNombreBBDD() {
        return nombreBBDD;
    }

    public int getPuerto() {
        return puerto;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordFieldLoginPass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBBDD;
    private javax.swing.JTextField jTextFieldHost;
    private javax.swing.JTextField jTextFieldLoginUsuario;
    private javax.swing.JTextField jTextFieldPuerto;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
