/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.MainBody;

import GUI.Main.Main;
import Logica.LogicaNegocio;
import Logica.LogicaTemas;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlueMoonLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlueSteelLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaMauveMetallicLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaSilverMoonLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaSkyMetallicLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import org.openide.util.Exceptions;

/**
 * Panel Ajustes
 *
 * @author Plam
 */
public class PanelAjustes extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    private List<LookAndFeel> listaLaf;
    private List<JLabel> listaLabelsH1;
    private List<JLabel> listaLabelsH2;
    private LogicaNegocio logica;
    private Graphics2D g;

    /**
     * Constructor
     */
    public PanelAjustes(JFrame frame, LogicaNegocio logica) {
        initComponents();
        setBorder(LogicaTemas.GET_TITLE_BORDER("AJUSTES"));

        this.logica = logica;

        listaLabelsH1 = new ArrayList<>();
        listaLabelsH1.add(jLabel10H1);
        listaLabelsH1.add(jLabel8);
        listaLabelsH1.add(jLabel4H1);
        listaLabelsH1.add(jLabel1);

        listaLabelsH2 = new ArrayList<>();
        listaLabelsH2.add(jLabel9);
        listaLabelsH2.add(jLabel3H2);
        listaLabelsH2.add(jLabel5H2);
        listaLabelsH2.add(jLabel6H2);
        listaLabelsH2.add(jLabel7H2);
        listaLabelsH2.add(jLabel8H2);
        listaLabelsH2.add(jLabel9H2);
        listaLabelsH2.add(jLabelH2);
        listaLabelsH2.add(jLabel10H2);

        listaLaf = new ArrayList<>();
        try {
            listaLaf.add(new SyntheticaBlackEyeLookAndFeel());
            listaLaf.add(new SyntheticaBlackMoonLookAndFeel());
            listaLaf.add(new SyntheticaBlueIceLookAndFeel());
            listaLaf.add(new SyntheticaBlueMoonLookAndFeel());
            listaLaf.add(new SyntheticaBlueSteelLookAndFeel());
            listaLaf.add(new SyntheticaMauveMetallicLookAndFeel());
            listaLaf.add(new SyntheticaSilverMoonLookAndFeel());
            listaLaf.add(new SyntheticaSkyMetallicLookAndFeel());
            listaLaf.add(new SyntheticaStandardLookAndFeel());
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }

        LogicaTemas.addListJLabel("JLabelH1Ajustes", listaLabelsH1);
        LogicaTemas.addListJLabel("JLabelH2Ajustes", listaLabelsH2);

        DefaultComboBoxModel<String> dcm = new DefaultComboBoxModel<>();
        for (LookAndFeel lfi : listaLaf) {
            dcm.addElement(lfi.getName());
        }
        comboboxLookAndFeel.setModel(dcm);

        jTextFieldHost1.setText(logica.getHost());
        jPasswordFieldpass.setText(logica.getPass());
        jTextFieldBBDDName1.setText(logica.getBBDDName());
        jTextFieldPuerto1.setText(logica.getPuerto() + "");
        jTextFieldUsuario1.setText(logica.getUser());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelH2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7H2 = new javax.swing.JLabel();
        jButtonBorrarRegistros = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sliderTexto1 = new javax.swing.JSlider();
        jLabel10H2 = new javax.swing.JLabel();
        jPasswordFieldpass = new javax.swing.JPasswordField();
        jLabel3H2 = new javax.swing.JLabel();
        jButtonConectar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jLabel9H2 = new javax.swing.JLabel();
        jPasswordField3PassConfirm = new javax.swing.JPasswordField();
        jTextFieldBBDDName1 = new javax.swing.JTextField();
        jButtonImportCopiaSeg = new javax.swing.JButton();
        jButtonIdentificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2H2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6H2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonCrearCopiaSeg = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10H1 = new javax.swing.JLabel();
        jCheckBox1H2 = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jButtoncambiarPass = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4H1 = new javax.swing.JLabel();
        comboboxLookAndFeel = new javax.swing.JComboBox<>();
        jTextFieldPuerto1 = new javax.swing.JTextField();
        jTextFieldHost1 = new javax.swing.JTextField();
        jTextFieldUsuario1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordFieldNewPass = new javax.swing.JPasswordField();
        jLabel5H2 = new javax.swing.JLabel();
        jLabel8H2 = new javax.swing.JLabel();
        jPasswordFieldPassActual = new javax.swing.JPasswordField();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabel4.setFont(LogicaTemas.TEXT_FONT);
        jLabel4.setForeground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Identificate como Administrador");

        jLabelH2.setFont(LogicaTemas.TEXT_FONT);
        jLabelH2.setForeground(new java.awt.Color(0, 102, 153));
        jLabelH2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelH2.setText("Cambiar Vista");

        jLabel6.setFont(LogicaTemas.TEXT_FONT);
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Nueva Contraseña");

        jLabel7H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel7H2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7H2.setText("BD name:");

        jButtonBorrarRegistros.setFont(LogicaTemas.BUTTON_FONT);
        jButtonBorrarRegistros.setText("Borrar Todos los Registros");
        jButtonBorrarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarRegistrosActionPerformed(evt);
            }
        });

        jLabel3.setFont(LogicaTemas.TEXT_FONT);
        jLabel3.setForeground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Cambia la contraseña del Administrador");

        sliderTexto1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTexto1StateChanged(evt);
            }
        });

        jLabel10H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel10H2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10H2.setText("Usuario:");

        jPasswordFieldpass.setFont(LogicaTemas.TEXT_FONT);

        jLabel3H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel3H2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3H2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3H2.setText("Tamaño del Texto");

        jButtonConectar.setFont(LogicaTemas.BUTTON_FONT);
        jButtonConectar.setText("Conectar");
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });

        jLabel7.setFont(LogicaTemas.TEXT_FONT);
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Confirma la Contraseña");

        jPasswordFieldPass.setFont(LogicaTemas.TEXT_FONT);
        jPasswordFieldPass.setToolTipText("Constraseña");

        jLabel9H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel9H2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9H2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9H2.setText("( Se ejecutara script para crear todas las tablas y registros )");
        jLabel9H2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jPasswordField3PassConfirm.setFont(LogicaTemas.TEXT_FONT);

        jTextFieldBBDDName1.setFont(LogicaTemas.TEXT_FONT);

        jButtonImportCopiaSeg.setFont(LogicaTemas.BUTTON_FONT);
        jButtonImportCopiaSeg.setText("Cargar copia de seguridad");
        jButtonImportCopiaSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportCopiaSegActionPerformed(evt);
            }
        });

        jButtonIdentificar.setFont(LogicaTemas.TEXT_FONT);
        jButtonIdentificar.setText("Identifica me");
        jButtonIdentificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIdentificarActionPerformed(evt);
            }
        });

        jLabel8.setFont(LogicaTemas.TEXT_FONT_H1);
        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setText("Estilos del Programa");

        jLabel2H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel2H2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2H2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2H2.setText("Nombre");

        jLabel1.setFont(LogicaTemas.TEXT_FONT_H1);
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar Usuarios y Contraseñas");

        jLabel6H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel6H2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6H2.setText("Puerto:");

        jLabel5.setFont(LogicaTemas.TEXT_FONT);
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Contraseña actual");

        jTextFieldNombre.setFont(LogicaTemas.TEXT_FONT);

        jButtonCrearCopiaSeg.setFont(LogicaTemas.BUTTON_FONT);
        jButtonCrearCopiaSeg.setText("Crear copia de seguridad");
        jButtonCrearCopiaSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCopiaSegActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10H1.setFont(LogicaTemas.TEXT_FONT_H1);
        jLabel10H1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel10H1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10H1.setText("Copia de seguridad");

        jCheckBox1H2.setFont(LogicaTemas.TEXT_FONT);
        jCheckBox1H2.setForeground(new java.awt.Color(0, 102, 153));
        jCheckBox1H2.setText("Copiar todos los registros ?");
        jCheckBox1H2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtoncambiarPass.setFont(LogicaTemas.BUTTON_FONT);
        jButtoncambiarPass.setText("Cambiar Contraseña");
        jButtoncambiarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncambiarPassActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Contraseña");

        jLabel4H1.setFont(LogicaTemas.TEXT_FONT_H1);
        jLabel4H1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel4H1.setText("Base de datos");

        comboboxLookAndFeel.setFont(LogicaTemas.TEXT_FONT);
        comboboxLookAndFeel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxLookAndFeelActionPerformed(evt);
            }
        });

        jTextFieldPuerto1.setFont(LogicaTemas.TEXT_FONT);

        jTextFieldHost1.setFont(LogicaTemas.TEXT_FONT);

        jTextFieldUsuario1.setFont(LogicaTemas.TEXT_FONT);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPasswordFieldNewPass.setFont(LogicaTemas.TEXT_FONT);

        jLabel5H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel5H2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5H2.setText("Host:");

        jLabel8H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel8H2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8H2.setText("Contraseña:");

        jPasswordFieldPassActual.setFont(LogicaTemas.TEXT_FONT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(8, Short.MAX_VALUE)
                        .addComponent(jLabel5H2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHost1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6H2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPuerto1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7H2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBBDDName1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(7, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1H2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelH2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(comboboxLookAndFeel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel3H2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sliderTexto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jButtonCrearCopiaSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jButtonBorrarRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jButtonImportCopiaSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel10H1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10H2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8H2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPasswordFieldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel9H2, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 9, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4H1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addComponent(jLabel2H2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNombre)
                                .addComponent(jPasswordFieldPass))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField3PassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtoncambiarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldPassActual)))
                    .addComponent(jButtonIdentificar, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                        .addComponent(jLabelH2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboboxLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2H2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonIdentificar)
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPasswordFieldPassActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPasswordFieldNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPasswordField3PassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel3H2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sliderTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4H1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5H2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldHost1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6H2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldPuerto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7H2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldBBDDName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10H2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8H2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPasswordFieldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9H2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox1H2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10H1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, Short.MAX_VALUE)
                                    .addComponent(jButtonImportCopiaSeg)
                                    .addGap(18, 18, Short.MAX_VALUE)
                                    .addComponent(jButtonBorrarRegistros)
                                    .addGap(18, 18, Short.MAX_VALUE)
                                    .addComponent(jButtonCrearCopiaSeg))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConectar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtoncambiarPass, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1173, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para cambiar los colores de la vista
     *
     * @param evt
     */
    private void comboboxLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxLookAndFeelActionPerformed
        Main.setLookAndFeel(listaLaf.get(comboboxLookAndFeel.getSelectedIndex()));
    }//GEN-LAST:event_comboboxLookAndFeelActionPerformed

    private void jButtoncambiarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncambiarPassActionPerformed
        //        if (!logica.getUsuario().isAdmin()) {
        //            JOptionPane.showMessageDialog(this, "NO tiene suficiente privilegios para esta operacion");
        //            return;
        //        }

        String pass = "";
        String newPass = "";
        String passConfirm = "";

        pass = String.valueOf(jPasswordFieldPassActual.getPassword());
        newPass = String.valueOf(jPasswordFieldNewPass.getPassword());
        passConfirm = String.valueOf(jPasswordField3PassConfirm.getPassword());

        if (pass.isEmpty() || passConfirm.isEmpty() || newPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No puedes dejar cambo vacio ! ", "OK", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!newPass.equals(passConfirm)) {
            JOptionPane.showMessageDialog(this, "Las dos contraseñas tienen que coincidir", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (logica.cambiarPass(pass, newPass) > 0) {
            logica.getUsuario().setAdmin(true); //asigna administrador a una variable sin actualizar NO FUNCIONA
            JOptionPane.showMessageDialog(this, "Contraseña cambiada con Exito", "OK", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtoncambiarPassActionPerformed

    private void jButtonCrearCopiaSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCopiaSegActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                if (logica.crearCopiaSeguridad()) {
                    JOptionPane.showMessageDialog(null, "Copia de seguridad creada", "OK", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Algo ha fallado al crear copia de seguridad ! ", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        Main.refrescarPaneles();
    }//GEN-LAST:event_jButtonCrearCopiaSegActionPerformed

    /**
     * Metodo para identificar el administrador
     *
     * @param evt
     */
    private void jButtonIdentificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIdentificarActionPerformed
        String pass = "";
        pass = String.valueOf(jPasswordFieldPass.getPassword());
        System.out.println(logica.cryptWithMD5(pass));
        if (pass.isEmpty()) {
            return;
        }

        if (logica.son2PassIguales(pass)) {
            logica.getUsuario().setAdmin(true);
            JOptionPane.showMessageDialog(this, "Ya tiene privilegios de administrador", "OK", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "La contraseña NO coincide con el del administrador", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIdentificarActionPerformed

    private void jButtonImportCopiaSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportCopiaSegActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                if (null != logica.getUsuario() && logica.getUsuario().isAdmin()) {
                    logica.cargarRegistros();
                    JOptionPane.showMessageDialog(null, "Registros importados con exito ! ", "OK", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "NO tienes suficiente permisos para cargar los registros", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                Main.refrescarPaneles();
            }
        });
        Main.refrescarPaneles();
    }//GEN-LAST:event_jButtonImportCopiaSegActionPerformed

    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                String host = jTextFieldHost1.getText();
                String port = jTextFieldPuerto1.getText();
                String bbdd = jTextFieldBBDDName1.getText();
                String user = jTextFieldUsuario1.getText();
                String pass = String.valueOf(jPasswordFieldpass.getPassword());
                boolean cargartablas = jCheckBox1H2.isSelected();

                int puerto = 0;
                try {
                    puerto = Integer.parseInt(port);
                } catch (NumberFormatException e) {
                    logger.error(e.getMessage());
                    return;
                }

                if (!host.isEmpty() && puerto > 0 && !bbdd.isEmpty() && !user.isEmpty() && !pass.isEmpty()) {
                    if (cargartablas) {
                        if (logica.cambiarConexion(user, pass, host, puerto, bbdd, true)) {
                            JOptionPane.showMessageDialog(null, "Conexion a la BBDD cambiada con exito !", "OK", JOptionPane.INFORMATION_MESSAGE);
                            logger.info("Conexion a la BBDD cambiada con exito !");
                        } else {
                            JOptionPane.showMessageDialog(null, "NO se ha podido cambiar la BBDD, revisa los datos", "ERROR", JOptionPane.ERROR_MESSAGE);
                            logger.info("NO se ha podido cambiar la BBDD");
                        }
                    } else {
                        if (logica.cambiarConexion(user, pass, host, puerto, bbdd, false)) {
                            JOptionPane.showMessageDialog(null, "Conexion a la BBDD cambiada con exito !", "OK", JOptionPane.INFORMATION_MESSAGE);
                            logger.info("Conexion a la BBDD cambiada con exito !");
                        } else {
                            JOptionPane.showMessageDialog(null, "NO se ha podido cambiar la BBDD, revisa los datos", "ERROR", JOptionPane.ERROR_MESSAGE);
                            logger.info("NO se ha podido cambiar la BBDD");
                        }
                    }

                }
                Main.refrescarPaneles();

            }
        });
    }//GEN-LAST:event_jButtonConectarActionPerformed

    /**
     * Metodo para cambiar el tamaño del texto
     *
     * @param evt
     */
    private void sliderTexto1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTexto1StateChanged
        int value = sliderTexto1.getValue();
        LogicaTemas.setTextSize(value / 3, value / 4);
        LogicaTemas.LISTA_TABLES.stream().forEach(table -> {
            table.paintComponents(g);
        });
    }//GEN-LAST:event_sliderTexto1StateChanged

    /**
     * Metodo para borrar todos los registros de la base de datos<br>Hacen falta
     * permisos de Administrador
     *
     * @param evt
     */
    private void jButtonBorrarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarRegistrosActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                if (null != logica.getUsuario() && logica.getUsuario().isAdmin()) {
                    int resp = JOptionPane.showConfirmDialog(null, "Estas seguro que quieres borrar todos los registros ?", "Atencion", JOptionPane.YES_NO_OPTION);
                    if (resp == JOptionPane.YES_OPTION) {
                        if (logica.borrarRegistros() > 0) {
                            JOptionPane.showMessageDialog(null, "Todos los registros borrados con exito !", "OK", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "NO tienes suficiente permisos para borrar los registros", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                Main.refrescarPaneles();
            }
        });
        Main.refrescarPaneles();
    }//GEN-LAST:event_jButtonBorrarRegistrosActionPerformed

    private static void setUIFont(javax.swing.plaf.FontUIResource f) {
        java.util.Enumeration<Object> keys = UIManager.getLookAndFeelDefaults().keys();
        while (keys.hasMoreElements()) {
            Object key = keys.nextElement();
            Object value = UIManager.get(key);
            if (value instanceof javax.swing.plaf.FontUIResource) {
                UIManager.put(key, f);
            }
        }
    }

    @Override
    public void print(Graphics grphcs) {
        super.print(grphcs); //To change body of generated methods, choose Tools | Templates.
        g = (Graphics2D) grphcs;
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs); //To change body of generated methods, choose Tools | Templates.

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxLookAndFeel;
    private javax.swing.JButton jButtonBorrarRegistros;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonCrearCopiaSeg;
    private javax.swing.JButton jButtonIdentificar;
    private javax.swing.JButton jButtonImportCopiaSeg;
    private javax.swing.JButton jButtoncambiarPass;
    private javax.swing.JCheckBox jCheckBox1H2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10H1;
    private javax.swing.JLabel jLabel10H2;
    private javax.swing.JLabel jLabel2H2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3H2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4H1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5H2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6H2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7H2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel8H2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel9H2;
    private javax.swing.JLabel jLabelH2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField3PassConfirm;
    private javax.swing.JPasswordField jPasswordFieldNewPass;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JPasswordField jPasswordFieldPassActual;
    private javax.swing.JPasswordField jPasswordFieldpass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldBBDDName1;
    private javax.swing.JTextField jTextFieldHost1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPuerto1;
    private javax.swing.JTextField jTextFieldUsuario1;
    private javax.swing.JSlider sliderTexto1;
    // End of variables declaration//GEN-END:variables
    private static final org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(PanelAjustes.class);
}
