/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.MainBody;

import Dto.Factura;
import Dto.Persona;
import GUI.Dialog.DialogFactura;
import GUI.Dialog.DialogPersona;
import Logica.LogicaNegocio;
import Logica.LogicaTemas;
import TableModels.FacturaTableModel;
import TableModels.PersonasTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 * Panel Compra
 * @author Plam
 */
public class PanelCompra extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    private LogicaNegocio logica;
    private List<JLabel> listaLabelsH2;
    private JFrame parent;
    /**
     * Constructor
     */
    public PanelCompra(JFrame frame, LogicaNegocio logica) {
        initComponents();
        setBorder(LogicaTemas.GET_TITLE_BORDER("Compras"));

        this.parent = frame;
        this.logica = logica;
        
        listaLabelsH2 = new ArrayList<>();
        listaLabelsH2.add(jLabel1H2);
        listaLabelsH2.add(jLabel3H2);

        LogicaTemas.addJTable(jTableProveedores);
        LogicaTemas.addJTable(jTableFacturasProveedores);
        
        LogicaTemas.addListJLabel("JLabelH2LibroDiario", listaLabelsH2);
        
        jTableProveedores.setModel(new PersonasTableModel(this.logica.getListaProveedores()));
        jTableFacturasProveedores.setModel(new FacturaTableModel(new ArrayList<>()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1H2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProveedores = new javax.swing.JTable();
        jLabel3H2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFacturasProveedores = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(901, 500));

        jLabel1H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel1H2.setText("Proveedores");

        jTableProveedores.setFont(LogicaTemas.TEXT_FONT);
        jTableProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProveedores);

        jLabel3H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel3H2.setText("Facturas ");

        jTableFacturasProveedores.setFont(LogicaTemas.TEXT_FONT);
        jTableFacturasProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFacturasProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFacturasProveedoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableFacturasProveedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1H2)
                            .addComponent(jLabel3H2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1H2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3H2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProveedoresMouseClicked
        if (jTableProveedores.getSelectedRow() != -1) {
            int ID_persona = (int) jTableProveedores.getValueAt(jTableProveedores.getSelectedRow(), 0);
            if (evt.getClickCount() > 1) {
                Persona persona = logica.getPersonaPorID(ID_persona);
                if (persona != null) {
                    DialogPersona df = new DialogPersona(parent, true, logica, persona);
                    df.setVisible(true);
                }
            } else {
                jTableFacturasProveedores.setModel(new FacturaTableModel(logica.getListaFacturas(ID_persona)));
            }
        } else {

        }
    }//GEN-LAST:event_jTableProveedoresMouseClicked

    private void jTableFacturasProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFacturasProveedoresMouseClicked
        if (evt.getClickCount() > 1) {
            if (jTableFacturasProveedores.getSelectedRow() != -1) {
                int ID_factura = (int) jTableFacturasProveedores.getValueAt(jTableFacturasProveedores.getSelectedRow(), 0);
                Factura factura = logica.getFacturaPorID(ID_factura);
                if (factura != null) {
                    DialogFactura df = new DialogFactura(parent, true, logica, factura);
                    df.setVisible(true);
                    jTableProveedores.setModel(new PersonasTableModel(logica.getListaProveedores()));
                }
            }
        }
    }//GEN-LAST:event_jTableFacturasProveedoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1H2;
    private javax.swing.JLabel jLabel3H2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableFacturasProveedores;
    private javax.swing.JTable jTableProveedores;
    // End of variables declaration//GEN-END:variables
    private static final org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(PanelCompra.class);
}
