/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.MainBody;

import Dto.Factura;
import Dto.Persona;
import GUI.Dialog.DialogFactura;
import GUI.Dialog.DialogPersona;
import Logica.LogicaNegocio;
import Logica.LogicaTemas;
import TableModels.FacturaTableModel;
import TableModels.PersonasTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 * Panel Venta
 *
 * @author Plam
 */
public class PanelVenta extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    private JFrame parent;

    //lista para todos labels para manejar el tamaño del texto
    private List<JLabel> listaLabelsH2;
    private LogicaNegocio logica;

    /**
     * Constructor
     */
    public PanelVenta(JFrame frame, LogicaNegocio logica) {
        initComponents();
        this.parent = frame;
        setBorder(LogicaTemas.GET_TITLE_BORDER("VENTAS"));

        this.logica = logica;
        listaLabelsH2 = new ArrayList<>();
        listaLabelsH2.add(jLabel1H2);
        listaLabelsH2.add(jLabel3H2);

        LogicaTemas.addJTable(jTableClientes);
        LogicaTemas.addJTable(jTableFacturasCliente);

        LogicaTemas.addListJLabel("JLabelH2LibroDiario", listaLabelsH2);

        jTableClientes.setModel(new PersonasTableModel(this.logica.getListaClientes()));
        jTableFacturasCliente.setModel(new FacturaTableModel(new ArrayList<>()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFacturasCliente = new javax.swing.JTable();
        jLabel1H2 = new javax.swing.JLabel();
        jLabel3H2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(901, 500));

        jTableClientes.setFont(LogicaTemas.TEXT_FONT);
        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jTableFacturasCliente.setFont(LogicaTemas.TEXT_FONT);
        jTableFacturasCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFacturasCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFacturasClienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableFacturasCliente);

        jLabel1H2.setText("Clientes");

        jLabel3H2.setText("Facturas ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1H2)
                            .addComponent(jLabel3H2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1H2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3H2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para actuar cuando el usuario a echo un click sobre la tabla de las facturas
     * Si se ha echo 2 veces click , se abre una ventana con la informacion de la factura
     * @param evt 
     */
    private void jTableFacturasClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFacturasClienteMouseClicked
        if (evt.getClickCount() > 1) {
            if (jTableFacturasCliente.getSelectedRow() != -1) {
                int ID_factura = (int) jTableFacturasCliente.getValueAt(jTableFacturasCliente.getSelectedRow(), 0);
                Factura factura = logica.getFacturaPorID(ID_factura);
                if (factura != null) {
                    DialogFactura df = new DialogFactura(parent, true, logica, factura);
                    df.setVisible(true);
                    jTableClientes.setModel(new PersonasTableModel(logica.getListaClientes()));
                }
            }
        }
    }//GEN-LAST:event_jTableFacturasClienteMouseClicked

    
    /**
     * Metodo para actualizar Panel Venta,
     * se refrescara la lista de clientes y se limpiara la tabla de las facturas
     *  evt 
     */
    public void actualizarPanelVenta(){
        jTableClientes.setModel(new PersonasTableModel(logica.getListaClientes()));
        jTableFacturasCliente.setModel(new FacturaTableModel(new ArrayList<>()));
        
    }
    
    /**
     * Metodo para actuar cuando el usuario a echo un click sobre la tabla de clientes
     * Si se ha echo 2 veces click , se abre una ventana con la informacion del cliente
     * @param evt 
     */
    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        if (jTableClientes.getSelectedRow() != -1) {
            int ID_persona = (int) jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0);
            if (evt.getClickCount() > 1) {
                Persona persona = logica.getPersonaPorID(ID_persona);
                if (persona != null) {
                    DialogPersona df = new DialogPersona(parent, true, logica, persona);
                    df.setVisible(true);
                }
            } else {
                jTableFacturasCliente.setModel(new FacturaTableModel(logica.getListaFacturas(ID_persona)));
            }
        } 
    }//GEN-LAST:event_jTableClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1H2;
    private javax.swing.JLabel jLabel3H2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTableFacturasCliente;
    // End of variables declaration//GEN-END:variables
    private static final org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(PanelVenta.class);
}
