/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.MainBody;

import Dto.Factura;
import Dto.Persona;
import GUI.Dialog.DialogFactura;
import GUI.Dialog.DialogProducto;
import Logica.LogicaNegocio;
import Logica.LogicaTemas;
import TableModels.FacturaTableModel;
import TableModels.PersonaCortoTableModel;
import TableModels.ProductoTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 * Panel Factura
 *
 * @author Plam
 */
public class PanelFacturas extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    private List<JLabel> listaLabelsH1;
    private List<JLabel> listaLabelsH2;
    private JFrame parent;
    private LogicaNegocio logica;
    private FacturaTableModel facturaTableModel;
    private ProductoTableModel productoTableModel;
    private PersonaCortoTableModel ptm;

    /**
     * Constructor
     */
    public PanelFacturas(JFrame parent, LogicaNegocio logica) {
        initComponents();
        this.parent = parent;
        this.logica = logica;

        setBorder(LogicaTemas.GET_TITLE_BORDER("Facturas"));

        jTableFacturas.setModel(new FacturaTableModel(logica.getTodasLasFacturas()));

        listaLabelsH1 = new ArrayList<>();
        listaLabelsH1.add(jLabel1H1);

        listaLabelsH2 = new ArrayList<>();
        listaLabelsH2.add(jLabel4H2);
        listaLabelsH2.add(jLabel5H2);
        listaLabelsH2.add(jLabel1H2);
        listaLabelsH2.add(jLabel11H2);

        LogicaTemas.addListJLabel("JLabelH1Facturas", listaLabelsH1);
        LogicaTemas.addListJLabel("JLabelH2Facturas", listaLabelsH2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel1H1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFacturas = new javax.swing.JTable();
        jButtonImprimir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4H2 = new javax.swing.JLabel();
        jLabel5H2 = new javax.swing.JLabel();
        jButtonNuevaFactura = new javax.swing.JButton();
        jButtonEditarFactura = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Productos = new javax.swing.JTable();
        jLabel1H2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11H2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(901, 500));

        jComboBoxTipo.setFont(LogicaTemas.TEXT_FONT);
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "CLIENTE", "PROVEEDOR" }));
        jComboBoxTipo.setBorder(null);
        jComboBoxTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jLabel1H1.setFont(LogicaTemas.TEXT_FONT_H1);
        jLabel1H1.setText("Filtrar por:");

        jButton1.setFont(LogicaTemas.BUTTON_FONT);
        jButton1.setText("Filtrar");

        jTableFacturas.setFont(LogicaTemas.TEXT_FONT);
        jTableFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFacturasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableFacturas);

        jButtonImprimir.setFont(LogicaTemas.BUTTON_FONT);
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel4H2.setText("facturas actuales:");

        jLabel5H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel5H2.setText("Cliente / Proveedor");

        jButtonNuevaFactura.setFont(LogicaTemas.BUTTON_FONT);
        jButtonNuevaFactura.setText("Nueva Factura");
        jButtonNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaFacturaActionPerformed(evt);
            }
        });

        jButtonEditarFactura.setFont(LogicaTemas.BUTTON_FONT);
        jButtonEditarFactura.setText("Ver Factura");
        jButtonEditarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarFacturaActionPerformed(evt);
            }
        });

        jTable1Productos.setFont(LogicaTemas.TEXT_FONT);
        jTable1Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1ProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1Productos);

        jLabel1H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel1H2.setText("Productos ");

        jTableCliente.setFont(LogicaTemas.TEXT_FONT);
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCliente);

        jLabel11H2.setFont(LogicaTemas.TEXT_FONT);
        jLabel11H2.setText("Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1H1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4H2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 133, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5H2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButtonNuevaFactura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonEditarFactura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonImprimir)))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                                .addComponent(jLabel1H2)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                                .addComponent(jSeparator2)
                                .addComponent(jLabel11H2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1H1)
                .addGap(29, 29, 29)
                .addComponent(jLabel5H2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4H2)
                    .addComponent(jLabel11H2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1H2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImprimir)
                    .addComponent(jButtonEditarFactura)
                    .addComponent(jButtonNuevaFactura))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para hacer factura nueva. Abre nueva ventana ! 
     * @param evt 
     */
    private void jButtonNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaFacturaActionPerformed
        DialogFactura dialog = new DialogFactura(parent, true, logica, null);
        dialog.setVisible(true);
        jTableFacturas.setModel(new FacturaTableModel(logica.getTodasLasFacturas()));
    }//GEN-LAST:event_jButtonNuevaFacturaActionPerformed

    /**
     * Metodo para editar una factura 
     * @param evt 
     */
    private void jButtonEditarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarFacturaActionPerformed
        if (jTableFacturas.getSelectedRow() != -1) {
            int ID_FACTURA = (Integer) jTableFacturas.getValueAt(jTableFacturas.getSelectedRow(), 0);
            Factura f = logica.getFacturaPorID(ID_FACTURA);
            DialogFactura dialog = new DialogFactura(parent, true, logica, f);
            dialog.setVisible(true);
            jTableFacturas.setModel(new FacturaTableModel(logica.getTodasLasFacturas()));
        }
    }//GEN-LAST:event_jButtonEditarFacturaActionPerformed

    /**
     * Metodo para manejar los click a la tabla de las facturas
     * @param evt 
     */
    private void jTableFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFacturasMouseClicked
        if (jTableFacturas.getSelectedRow() == -1) {
            return;
        }
        int ID_factura = (Integer) jTableFacturas.getValueAt(jTableFacturas.getSelectedRow(), 0);
        if (ID_factura != -1 && evt.getClickCount() >= 2) {
            DialogFactura dialog = new DialogFactura(parent, true, logica, logica.getFacturaPorID(ID_factura));
            dialog.setVisible(true);
        }
        if (ID_factura != -1) {
            productoTableModel = new ProductoTableModel(logica.getProductosPorFactura(ID_factura));
            jTable1Productos.setModel(productoTableModel);

            Persona p = logica.getPersonaPorIDFactura(ID_factura);
            List<Persona> lista = new ArrayList<>();
            lista.add(p);
            ptm = new PersonaCortoTableModel(lista);
            jTableCliente.setModel(ptm);
        }

    }//GEN-LAST:event_jTableFacturasMouseClicked

    /**
     * Metodo para manejar los eventos del jComboBox<br> 
     * se cambia entre clientes, proveedores y todos
     * @param evt 
     */
    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed

        java.awt.EventQueue.invokeLater(() -> {
            switch (jComboBoxTipo.getSelectedIndex()) {
                case 1:
                    jTableFacturas.setModel(new FacturaTableModel(logica.getFacturasClientes()));
                    break;
                case 2:
                    jTableFacturas.setModel(new FacturaTableModel(logica.getFacturasProveedores()));
                    break;
                default:
                    jTableFacturas.setModel(new FacturaTableModel(logica.getTodasLasFacturas()));
                    break;
            }
        });
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    /**
     * Metodo para manejar los clock de la table de los productos
     * @param evt 
     */
    private void jTable1ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1ProductosMouseClicked
        if (jTable1Productos.getSelectedRow() == -1) {
            return;
        }
        int ID_producto = (int) jTable1Productos.getValueAt(jTable1Productos.getSelectedRow(), 0);
        if (ID_producto != -1 && evt.getClickCount() == 2) {
            DialogProducto dialog = new DialogProducto(parent, true, logica, logica.getProductoPorID(ID_producto));
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jTable1ProductosMouseClicked

    
    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableClienteMouseClicked

    /**
     * Metodo para imprimir una factura en pdf
     * @param evt 
     */
    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        if (jTableFacturas.getSelectedRow() == -1) {
            return;
        }
        int ID_factura = (int) jTableFacturas.getValueAt(jTableFacturas.getSelectedRow(), 0);
        if (ID_factura != -1) {
            logica.imprimirInformeFactura(logica.getFacturaPorID(ID_factura));
        }
    }//GEN-LAST:event_jButtonImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEditarFactura;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonNuevaFactura;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel11H2;
    private javax.swing.JLabel jLabel1H1;
    private javax.swing.JLabel jLabel1H2;
    private javax.swing.JLabel jLabel4H2;
    private javax.swing.JLabel jLabel5H2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1Productos;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableFacturas;
    // End of variables declaration//GEN-END:variables
    private static final org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(PanelFacturas.class);
}
